<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sabari" failures="0" tests="5" name="com.ecommerceDomain.Scripts.TestCase2" time="88.099" errors="1" timestamp="2022-08-30T16:54:19 IST" skipped="0">
  <testcase classname="com.ecommerceDomain.Scripts.TestCase2" name="testcase2" time="21.680"/>
  <system-out/>
  <testcase classname="com.ecommerceDomain.Scripts.TestCase2" name="testcase2" time="21.500"/>
  <system-out/>
  <testcase classname="com.ecommerceDomain.Scripts.TestCase2" name="configAS" time="4.249">
    <error message="Cannot invoke &quot;java.sql.Connection.close()&quot; because &quot;com.ecommerceDomain.Wipro.genericlib.FileUtilities.con&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "com.ecommerceDomain.Wipro.genericlib.FileUtilities.con" is null
at com.ecommerceDomain.Wipro.genericlib.FileUtilities.closedb(FileUtilities.java:99)
at com.ecommerceDomain.Wipro.genericlib.BaseClass.configAS(BaseClass.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- configAS -->
  <system-out/>
  <testcase classname="com.ecommerceDomain.Scripts.TestCase2" name="testcase2" time="22.014"/>
  <system-out/>
  <testcase classname="com.ecommerceDomain.Scripts.TestCase2" name="testcase2" time="18.656"/>
  <system-out/>
</testsuite> <!-- com.ecommerceDomain.Scripts.TestCase2 -->
